[0m02:44:10.140194 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A28BA3FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A2AF83370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A2B53C160>]}


============================== 02:44:10.146704 | 8ee3f4e2-03c7-40fe-9b6e-29c47c5e2459 ==============================
[0m02:44:10.146704 [info ] [MainThread]: Running with dbt=1.8.0
[0m02:44:10.147704 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\app_a\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt ', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:44:10.148705 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m02:44:10.150214 [debug] [MainThread]: Command `cli deps` failed at 02:44:10.149705 after 0.09 seconds
[0m02:44:10.150214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A28BA3FA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A2B5B1100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A2B5B1190>]}
[0m02:44:10.151227 [debug] [MainThread]: Flushing usage events
[0m02:46:47.716929 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026350522430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026351045220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000263528E20D0>]}


============================== 02:46:47.722916 | 1ff40b28-3373-4bdc-8630-83be7fe86bc0 ==============================
[0m02:46:47.722916 [info ] [MainThread]: Running with dbt=1.8.0
[0m02:46:47.723913 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\app_a\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt ', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:46:47.724930 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m02:46:47.725451 [debug] [MainThread]: Command `cli deps` failed at 02:46:47.725451 after 0.22 seconds
[0m02:46:47.726468 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026350522430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026352F111C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026352F111F0>]}
[0m02:46:47.726468 [debug] [MainThread]: Flushing usage events
